- name: Install apache, start apache, deploy 
  hosts: web
  become: yes
  
  tasks:
    - name: Instal apache
      dnf:
        name: httpd
        state: present
    - name: Start apache
      service:
        name: httpd
        state: started
    - name: Enable apache
      service:
        name: httpd
        enabled: on # yes
    - name: Deploy the static file
      copy:
        src: /home/ec2-user/research/index.html
        dest: /var/www/html/
      
